# title: "CD20-data_1st_line therapy"
# output: html_document
# date: "2025-12-18"
# Author: Sanaz M. Gholy, Christian Brieghel 
#---

library(data.table)
library(tidyverse)
library(dplyr)
library(tidyr)
library(arrow)
library(lubridate)

setwd("/ngc/projects2/dalyca_r/sangho_r/data/CD20_final_data_SG")
cohort <- fread("CD20_cohort_20251203.txt")

source('/ngc/projects2/dalyca_r/clean_r/load_dalycare_package.R') 
load_dataset(c('t_dalycare_diagnoses', 'patient', 'RKKP_LYFO' ))

LYFO_clean = RKKP_LYFO %>% 
  clean_RKKP_LYFO()

LYFO_clean %>% select(matches('2nd')) %>% names

#1L####
cohort1 <- cohort%>%
  left_join(LYFO_clean %>% 
              select(patientid, immunotherapy_type_1st_line , 
                     chemo_regime_1_type_1st_line, 
                     chemo_regime_2_type_1st_line,
                     chemo_regime_3_type_1st_line), by='patientid')
n_distinct(cohort1)

#Categorising_chemoregime####
cohort2 <- cohort1 %>% 
  mutate(treatment_type_1 =paste(chemo_regime_1_type_1st_line, chemo_regime_2_type_1st_line, chemo_regime_3_type_1st_line),
         treatment_type_1st_line = recode(treatment_type_1,
                                          `abvd NA NA` = 'Other', 
                                          `acvd hdmtx NA` = 'Other', 
                                          `bac bendamustin NA` = 'Bendamustine/BAC', 
                                          `bac hdarac NA` = 'Bendamustine/BAC', 
                                          `bac NA NA` = 'Bendamustine/BAC', 
                                          `bendamustin chop hdmtx` = 'CHOP + HD-MTX', 
                                          `bendamustin chop NA` = 'CHOP', 
                                          `bendamustin cvp NA` = 'Bendamustine/BAC', 
                                          `bendamustin cyclofosfamid NA` = 'Bendamustine/BAC', 
                                          `bendamustin epoch hdmtx` = 'EPOCH-R', 
                                          `bendamustin hdmtx NA` = 'Bendamustine/BAC', 
                                          `bendamustin ibrutinib NA` = 'Other', 
                                          `bendamustin lenalidomid NA` = 'Bendamustine/BAC', 
                                          `bendamustin NA NA` = 'Bendamustine/BAC', 
                                          `bendamustin velcade NA` = 'Bendamustine/BAC', 
                                          `bfm choep hdmtx` = 'CHOP + HD-MTX', 
                                          `bfm chop NA` = 'CHOP', 
                                          `bfm dhap NA` = 'Other', 
                                          `bfm NA NA` = 'Other', 
                                          `cap velcade NA` = 'Other', 
                                          `ccvp NA NA` = 'Other', 
                                          `ceop hdarac NA` = 'CHOP', 
                                          `ceop hdmtx itbehandling` = 'CHOP', 
                                          `ceop itbehandling NA` = 'CHOP', 
                                          `ceop NA NA` = 'CHOP', 
                                          `chic itbehandling hdctx` = 'Bio-CHIC', 
                                          `chic NA NA` = 'Bio-CHIC', 
                                          `chlorambucil cop fcd` = 'Other',
                                          `chlorambucil NA NA` = 'Other',
                                          `choep bfm dhap` = 'xx', 
                                          `choep choep hdmtx` = 'CHOP',
                                          `choep chop hdmtx` = 'CHOP + HD-MTX', 
                                          `choep chop NA` = 'CHOP', 
                                          `choep hdarac hdmtx` = 'CHOP', 
                                          `choep hdarac NA` = 'CHOP', 
                                          `choep hdmtx choep` = 'CHOP + HD-MTX', 
                                          `choep hdmtx hdarac` = 'CHOP + HD-MTX', 
                                          `choep hdmtx hdmtx` = 'CHOP + HD-MTX', 
                                          `choep hdmtx ice` = 'CHOP + HD-MTX',
                                          `choep hdmtx NA` = 'CHOP + HD-MTX', 
                                          `choep itbehandling NA` = 'CHOP',
                                          `choep NA NA` = 'CHOP', 
                                          `chop bendamustin NA` = 'CHOP', 
                                          `chop bfm NA` = 'CHOP', 
                                          `chop ccvp NA` = 'CHOP', 
                                          `chop ceop NA` = 'CHOP',
                                          `chop chlorambucil NA` = 'CHOP', 
                                          `chop choep hdmtx` = 'CHOP + HD-MTX', 
                                          `chop choep NA` = 'CHOP',
                                          `chop chop hdmtx` = 'CHOP + HD-MTX',
                                          `chop chop NA` = 'CHOP', 
                                          `chop codoxmivac minibeam` = 'Other',
                                          `chop codoxmivac NA` = 'Other', 
                                          `chop cop NA` = 'CHOP', 
                                          `chop cope NA` = 'CHOP', 
                                          `chop cvp NA` = 'CHOP', 
                                          `chop cyclofosfamid doxorubicin` = 'CHOP',
                                          `chop cyclofosfamid NA` = 'CHOP', 
                                          `chop dhap beam` = 'CHOP',
                                          `chop dhap NA` = 'CHOP', 
                                          `chop epoch hdmtx` = 'EPOCH-R', 
                                          `chop epoch itbehandling` = 'EPOCH-R', 
                                          `chop fcd NA` = 'CHOP', 
                                          `chop hdarac bendamustin` = 'CHOP',
                                          `chop hdarac cyclofosfamid` = 'CHOP',
                                          `chop hdarac hdctx` = 'CHOP', 
                                          `chop hdarac hdmtx` = 'CHOP + HD-MTX', 
                                          `chop hdarac NA` = 'CHOP',
                                          `chop hdmtx ceop` = 'CHOP + HD-MTX',
                                          `chop hdmtx choep` = 'CHOP + HD-MTX',
                                          `chop hdmtx chop` = 'CHOP + HD-MTX',
                                          `chop hdmtx epoch` = 'EPOCH-R',
                                          `chop hdmtx hdarac` = 'CHOP + HD-MTX', 
                                          `chop hdmtx itbehandling` = 'CHOP + HD-MTX',
                                          `chop hdmtx NA` = 'CHOP + HD-MTX',
                                          `chop hdmtx oncovin` = 'CHOP + HD-MTX', 
                                          `chop ice NA` = 'CHOP', 
                                          `chop ifos hdmtx` = 'CHOP + HD-MTX', 
                                          `chop itbehandling bac` = 'CHOP', 
                                          `chop itbehandling hdmtx` = 'CHOP + HD-MTX', 
                                          `chop itbehandling ifos` = 'CHOPe', 
                                          `chop itbehandling NA` = 'CHOP', 
                                          `chop mantle2 NA` = 'maxi-CHOP',
                                          `chop maxichop hdarac` = 'maxi-CHOP',
                                          `chop maxichop NA` = 'maxi-CHOP', 
                                          `chop minichop NA` = 'CHOP', 
                                          `chop NA beam` = 'CHOP', 
                                          `chop NA chop` = 'CHOP',
                                          `chop NA NA` = 'CHOP',
                                          `chop oncovin NA` = 'CHOP', 
                                          `chop velcade NA` = 'CHOP',
                                          `cns_ielsg NA NA` = 'CNS', 
                                          `cns_matrix ice NA` = 'CNS',
                                          `cns_matrix NA NA` = 'MATRIX', 
                                          `cns_mvbp NA NA` = 'CNS', 
                                          `cns_mvp chop cns_mvp` = 'CNS',
                                          `cns_mvp hdarac NA` = 'CNS', 
                                          `cns_mvp hdmtx temozolomid` = 'CNS',
                                          `cns_mvp NA NA` = 'CNS',
                                          `cns_mvp temozolomid NA` = 'CNS', 
                                          `cnsbonn NA NA` = 'CNS', 
                                          `codoxmivac choep hdmtx` = 'Other',
                                          `codoxmivac chop hdmtx` = 'Other',
                                          `codoxmivac epoch hdmtx` = 'Other', 
                                          `codoxmivac NA NA` = 'Other',
                                          `cop chop cope` = 'CHOP', 
                                          `cop chop NA` = 'CHOP', 
                                          `cop fcd NA` = 'Other', 
                                          `cop NA NA` = 'Other', 
                                          `cope chop NA` = 'CHOP',
                                          `cope hdmtx NA` = 'CHOP + HD-MTX', 
                                          `cope NA NA` = 'CHOP', 
                                          `cvp bendamustin NA` = 'Bendamustine/BAC',
                                          `cvp ceop NA` = 'CHOP', 
                                          `cvp chlorambucil NA` = 'CHOP',
                                          `cvp chop chop` = 'CHOP', 
                                          `cvp chop NA` = 'CHOP',
                                          `cvp cope NA` = 'CHOP', 
                                          `cvp doxorubicin itbehandling` = 'Other',
                                          `cvp doxorubicin NA` = 'CVP', 
                                          `cvp fcd cyclofosfamid` = 'CVP', 
                                          `cvp fcd NA` = 'CVP', 
                                          `cvp hdarac NA` = 'CVP', 
                                          `cvp NA chop` = 'CHOP', 
                                          `cvp NA NA` = 'CVP', 
                                          `cvp oncovin NA` = 'CVP', 
                                          `cyclofosfamid bendamustin NA` = 'Bendamustine/BAC', 
                                          `cyclofosfamid doxorubicin velcade` = 'Other', 
                                          `cyclofosfamid NA NA` = 'Other',
                                          `cyclofosfamid velcade lenalidomid` = 'Other',
                                          `dhap hdarac NA` = 'Other',
                                          `dhap NA NA` = 'Other', 
                                          `doxorubicin NA NA` = 'Other', 
                                          `epoch hdmtx NA` = 'EPOCH-R', 
                                          `epoch NA NA` = 'EPOCH-R', 
                                          `fcd NA NA` = 'Other', 
                                          `fludarabin cyclofosfamid NA` = 'Other', 
                                          `hdarac ceop NA` = 'Other', 
                                          `hdarac chop NA` = 'CHOP', 
                                          `hdarac NA NA` = 'Other', 
                                          `hdmtx chop hdarac` = 'CHOP + HD-MTX',
                                          `hdmtx chop NA` = 'CHOP + HD-MTX', 
                                          `hdmtx cns_matrix NA` = 'CNS',
                                          `hdmtx cnsbonn NA` = 'CNS', 
                                          `hdmtx hdarac NA` = 'CNS', 
                                          `hdmtx ifos hdarac` = 'CNS',
                                          `hdmtx itbehandling NA` = 'CNS',
                                          `hdmtx NA NA` = 'CNS',
                                          `hdmtx peroral NA` = 'Other', 
                                          `hdmtx temozolomid NA` = 'CNS', 
                                          `hypercvad hdarac hdctx` = 'Other',
                                          `ibrutinib lenalidomid NA` = 'Other', 
                                          `ibrutinib NA NA` = 'Other' , 
                                          `ice NA NA` = 'Other', 
                                          `ifos hdarac bendamustin` = 'Bendamustine/BAC', 
                                          `ifos hdmtx hdarac` = 'Other',
                                          `ifos hdmtx NA` = 'Other',
                                          `interferon NA NA` = 'R-monotherapy',
                                          `itbehandling choep hdmtx` = 'CHOP + HD-MTX',
                                          `itbehandling chop NA` = 'CHOP',
                                          `itbehandling cyclofosfamid oncovin` = 'Other',
                                          `itbehandling hdmtx bcnu` = 'Other', 
                                          `itbehandling NA NA` = 'R-monotherapy',
                                          `lenalidomid NA NA` = 'Other', 
                                          `mantle2 NA NA` = 'MCL', 
                                          `mantle3 chop NA` = 'MCL', 
                                          `mantle3 NA NA` = 'MCL', 
                                          `maxichop chop cvp` = 'maxi-CHOP',
                                          `maxichop cladribin NA` = 'maxi-CHOP',
                                          `maxichop hdarac beam` = 'MCL', 
                                          `maxichop hdarac chop` = 'MCL',
                                          `maxichop hdarac itbehandling` = 'MCL',
                                          `maxichop hdarac NA` = 'MCL',
                                          `maxichop NA NA` = 'MCL', 
                                          `maximime hdmtx NA` = 'Other', 
                                          `minichop cvp NA` = 'CHOP',
                                          `minichop itbehandling NA` = 'CHOP',
                                          `minichop NA NA` = 'CHOP', 
                                          `mopp NA NA` = 'Other',
                                          `mvbpcns hdmtx chop` = 'CNS',
                                          `NA NA NA` = 'R-monotherapy',
                                          `nordiskcns NA NA` = 'CNS',
                                          `oncovin chop NA` = 'CHOP', 
                                          `oncovin cvp NA` = 'CVP',
                                          `oncovin cyclofosfamid choep` = 'CHOP', 
                                          `oncovin NA NA` = 'R-monotherapy',
                                          `temozolomid NA NA` = 'CNS',
                                          `triangle NA NA` = 'MCL', 
                                          `velcade NA NA` = 'Other',
                                          `vorinostat NA NA` = 'R-monotherapy'))


n_distinct(cohort2$treatment_type_1st_line)
n_distinct(cohort2$patientid) 
cohort2$treatment_type_1st_line %>% unique %>% sort %>% paste0(collapse = "` = 'xx', `")

colSums(is.na(cohort2))#So everyone has a registerede first line therapy
n_distinct(cohort2$patientid)

#fwrite(cohort2, file = "chemo_1stline.txt", sep="\t") 
#This is read in CD20_cohort_baseline_SG script where i gather all baseline that, and later make table 1
